import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Flutter Preview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            margin: 40,
          }}
        >
          <h1>Flutter Preview</h1>
          <br />
          <p>
            This is a preview of the Flutter Preview extension for VSCode. It
            allows you to preview Flutter widgets in the browser. To use it,
            visit <Link href="/app">/app</Link> and open the
            <code>Flutter Preview</code> panel in VSCode.
          </p>
        </div>
      </main>
    </>
  );
}
